# Build Stage
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production Stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY docker-entrypoint.d/40-backend-url.sh /docker-entrypoint.d/40-backend-url.sh
RUN sed -i 's/\r$//' /docker-entrypoint.d/40-backend-url.sh && chmod +x /docker-entrypoint.d/40-backend-url.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
